// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://icddhivznhfxeltdbjvh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImljZGRoaXZ6bmhmeGVsdGRianZoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MDYxNDUsImV4cCI6MjA2Njk4MjE0NX0.6mqt2KKJCYKqGdnDlmzQpBuur2LiOgKUdcSZuRrvxTo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});